config/routes.rb
Rails.application.routes.draw do
  devise_for :admin, skip: [:registrations, :passwords]

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  resources :news, only: [:index, :show]

  get '/conferences/future',  to: 'conferences#future'
  get '/conferences/ended',   to: 'conferences#ended'
  get '/conference/:id',      to: 'conferences#show', as: 'show_conference'

  get '/monograph/future',    to: 'monographs#future'
  get '/monograph/ended',     to: 'monographs#ended'

  post '/member_registration', to: 'conferences#registration', as: 'conference_registration'
  post '/add_monograph_editor', to: 'monographs#registration', as: 'monograph_registration'

  resources :contacts, only: [:index, :create]

  root 'main#index'
end

app/models/admin.rb
class Admin
  include Mongoid::Document
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable

  attr_accessor :login

  ## Database authenticatable
  field :email,              type: String, default: ""
  field :encrypted_password, type: String, default: ""
  field :username,           type: String

  ## Recoverable
  field :reset_password_token,   type: String
  field :reset_password_sent_at, type: Time

  ## Rememberable
  field :remember_created_at, type: Time

  ## Trackable
  field :sign_in_count,      type: Integer, default: 0
  field :current_sign_in_at, type: Time
  field :last_sign_in_at,    type: Time
  field :current_sign_in_ip, type: String
  field :last_sign_in_ip,    type: String

  ## Confirmable
  # field :confirmation_token,   type: String
  # field :confirmed_at,         type: Time
  # field :confirmation_sent_at, type: Time
  # field :unconfirmed_email,    type: String # Only if using reconfirmable

  ## Lockable
  # field :failed_attempts, type: Integer, default: 0 # Only if lock strategy is :failed_attempts
  # field :unlock_token,    type: String # Only if unlock strategy is :email or :both
  # field :locked_at,       type: Time

  def self.find_for_database_authentication conditions
    login = conditions.delete(:login)
    any_of({username: login}, email: login).first
  end
end

app/models/conference.rb
class Conference
  include Mongoid::Document
  include Mongoid::Timestamps

  has_many :conference_members
  embeds_many :documents

  accepts_nested_attributes_for :documents

  before_create :change_conference_status

  field :name,        type: String
  field :description, type: String
  field :start_date,  type: Date
  field :ended,       type: Mongoid::Boolean

  validates :name, :start_date, presence: true

  mount_uploader :file_ua, PdfUploader
  mount_uploader :file_en, PdfUploader

  def change_conference_status
    self.ended = true if self.start_date < Date.today
  end

  def self.update_conferences_status
    each do |conference|
      conference.update_attributes(ended: true) if self.start_date < Date.today
    end
  end
end

app/models/conference_member.rb
class ConferenceMember
  include Mongoid::Document
  include Mongoid::Timestamps

  belongs_to :conference

  field :first_name,        type: String
  field :last_name,         type: String
  field :surname,           type: String
  field :position,          type: String
  field :organization,      type: String
  field :academic_status,   type: String
  field :scientific_degree, type: String
  field :contry,            type: String
  field :city,              type: String
  field :address,           type: String
  field :phone,             type: String
  field :email,             type: String

  validates :first_name, :last_name, :surname, :contry, :city, :address, :phone, :email, presence: true

  def full_name
    "#{self.first_name} #{self.last_name} #{self.surname}"
  end
end

app/models/document.rb
class Document
  include Mongoid::Document

  embedded_in :conference

  field :name, type: String

  mount_uploader :file, PdfUploader
end

app/models/message.rb
class Message
  include Mongoid::Document
  include Mongoid::Timestamps

  field :first_name, type: String
  field :second_name, type: String
  field :email, type: String
  field :phone, type: String
  field :question, type: String

  validates :first_name, :second_name, :email, :phone, :question, presence: true
end

app/models/monograph.rb
class Monograph
  include Mongoid::Document
  include Mongoid::Timestamps

  has_many :monograph_editors

  field :name,          type: String
  field :authors,       type: String
  field :author_email,  type: String
  field :published,     type: Mongoid::Boolean

  validates :name, :authors, :author_email, presence: true

  mount_uploader :file, PdfUploader
end

app/models/monograph_editor.rb
class MonographEditor
  include Mongoid::Document
  include Mongoid::Timestamps

  belongs_to :monograph

  field :first_name,  type: String
  field :last_name,   type: String
  field :surname,     type: String
  field :phone,       type: String
  field :email,       type: String

  validates :first_name, :last_name, :surname, :email, presence: true

  def full_name
    "#{self.first_name} #{self.last_name} #{self.surname}"
  end
end

app/models/news.rb
class News
  include Mongoid::Document
  include Mongoid::Timestamps

  field :name, type: String
  field :description, type: String
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_in, keys: [:login, :password])
  end
end

app/controllers/conferences_controller.rb
class ConferencesController < ApplicationController
	def future
		@conferences = Conference.where(ended: false)
	end

	def ended
		@conferences = Conference.where(ended: true).paginate(page: params[:page], per_page: 5)
	end

	def show
		@conference = Conference.find(params[:id])
	end

	def registration
    conference = Conference.find(params[:conference_id])
    conference.conference_members.create!(member_params)

    redirect_to conferences_future_path
  end

  private

  def member_params
    params.permit(
      :first_name,
      :last_name,
      :surname,
      :position,
      :organization,
      :contry,
      :city,
      :address,
      :phone,
      :email,
			:academic_status,
			:scientific_degree,
			:conference_id
    )
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def index; end

  def create
    Message.create!(message_params)
    redirect_to contacts_url
  end

  private

  def message_params
    params.permit(:first_name, :second_name, :email, :phone, :question)
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index; end
end

app/controllers/monographs_controller.rb
class MonographsController < ApplicationController
  def future
    @monographs = Monograph.where(published: false).paginate(page: params[:page], per_page: 6)
  end

  def ended
    @monographs = Monograph.where(published: true).paginate(page: params[:page], per_page: 6)
  end

  def registration
    @monograph = Monograph.find(params[:monograph_id])
    @monograph.monograph_editors.create(registration_params)

    redirect_to monograph_future_url
  end

  private

  def registration_params
    params.permit(:first_name, :last_name, :surname, :email, :phone)
  end
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  def index
    @news = News.all.paginate(page: params[:page], per_page: 5)
  end

  def show
    @news = News.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/conferences_helper.rb
module ConferencesHelper
  def academic_status
    ['-', 'Доцент', 'Професор', 'Старший науковий співробітник', 'Старший дослідник']
  end

  def scientific_degree
    ['-', 'Кандидат наук', 'Доктор філософії', 'Доктор наук']
  end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/monographs_helper.rb
module MonographsHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/views/conferences/ended.html.haml
%main.main-container
  .container
    .row
      %h1.title-wrapper Проведені конференції
    - @conferences.each_slice(5) do |conference_items|
      .row
        - conference_items.first(3).each do |conference|
          .col-md-4.news-box
            .box-item
              %span.date
                = conference.start_date
              %span.title
                = conference.name
              = link_to 'Читати далі...', show_conference_url(conference.id), class: 'about-link'
      - if conference_items.count > 3
        .row
          - conference_items.last(2).each do |conference|
            .col-md-6.news-box
              .box-item
                %span.date
                  = conference.start_date
                %span.title
                  = conference.name
                = link_to 'Читати далі...', show_conference_url(conference.id), class: 'about-link'
    .row
      %nav.pull-right
        = will_paginate @confereces, {renderer: BootstrapPagination::Rails, previous_label: '<<', next_label: '>>'}

app/views/conferences/future.html.haml
%main.main-container
  .container.text-center
    .row
      %h1 Майбутні конференції
    - @conferences.each do |conference|
      .content-conference-future
        .row
          .col-md-6.news-box
            .box-item
              %span.date файл PDF
              %span.date UA
              %span.title Інформаційне повідомлення
              = link_to 'Завантажити', conference.file_ua_url, {class: 'about-link'}
          .col-md-6.news-box
            .box-item
              %span.date file PDF
              %span.date EN
              %span.title Information message
              = link_to 'Download', conference.file_en_url, {class: 'about-link'}
        .row
          .col-md-12.news-box.request-conferences
            .box-item
              %span.date
                = conference.start_date
              %span.title
                = conference.name
              = content_tag(:button, content_tag(:span, 'Зареєструватись на участь'), class:['js-request','about-link'], data: {id: conference.id.to_s})
#js-modal-request.modal-request-conferences
  #js-close-modal.close-modal
    %span.glyphicon.glyphicon-remove
  = form_with url: conference_registration_url, local: true do |f|
    .group
      = f.hidden_field :conference_id, id: 'object-id'
      = f.text_field :first_name, { required: true }
      %span.highlight
      %span.bar
      = f.label :first_name, 'Прізвище'
    .group
      = f.text_field :last_name, { required: true }
      %span.highlight
      %span.bar
      = f.label :last_name, 'Імʼя'
    .group
      = f.text_field :surname, { required: true }
      %span.highlight
      %span.bar
      = f.label :surname, 'По батькові'
    .group
      = f.select :academic_status, academic_status, prompt: 'Науковий ступінь'
    .group
      = f.select :scientific_degree, scientific_degree, prompt: 'Вчене звання'
    .group
      = f.text_field :position
      %span.highlight
      %span.bar
      = f.label :position, 'Посада'
    .group
      = f.text_field :organization
      %span.highlight
      %span.bar
      = f.label :organization, 'Організація'
    .group
      = f.text_field :contry, { required: true }
      %span.highlight
      %span.bar
      = f.label :contry, 'Країна'
    .group
      = f.text_field :city, { required: true }
      %span.highlight
      %span.bar
      = f.label :city, 'Місто'
    .group
      = f.text_field :address, { required: true }
      %span.highlight
      %span.bar
      = f.label :address, 'Адреса'
    .group
      = f.text_field :phone, { required: true }
      %span.highlight
      %span.bar
      = f.label :phone, 'Телефон'
    .group
      = f.text_field :email, { required: true }
      %span.highlight
      %span.bar
      = f.label :email, 'E-mail'
    .btn-box
      = f.submit 'Відправити', { class: 'btn btn-submit' }

app/views/conferences/show.html.haml
.container
  .row
    .col-xs-12
      %h1.title__item-news
        = @conference.name
      -# .image__item-news
        %img.img-responsive{:alt => "", :src => "img/slider/1.jpg"}/
      %span.date__item-news
        = @conference.created_at.strftime("%Y-%m-%d")
      .text-container__item-news
        %p
          = @conference.description
      .documents-container
        - @conference.documents.each do |document|
          .documet
            = link_to document.name, document.file_url

app/views/contacts/index.html.haml
%main.main-container
  .container
    .row
      .maps-contacts
        #map
    .row
      .about-us__form
        = form_with url: contacts_url, local: true do |f|
          %h3.title-form Напишіть нам
          .group
            = f.text_field :first_name, { required: true }
            %span.highlight
            %span.bar
            = f.label :first_name, 'Прізвище'
          .group
            = f.text_field :second_name, { required: true }
            %span.highlight
            %span.bar
            = f.label :second_name,  'Ім\'я'
          .group
            = f.email_field :email, { required: true }
            %span.highlight
            %span.bar
            = f.label :email, 'E-mail'
          .group
            = f.text_field :phone, { required: true }
            %span.highlight
            %span.bar
            = f.label :phone, 'Телефон'
          .group.textarea-container
            = f.text_area :question, { required: true }
            = f.label :question, 'Ваше питання', class: 'lebel-textarea'
          .btn-box
            = f.submit 'Відправити', class: 'btn btn-submit'
%script{:crossorigin => "anonymous", :integrity => "sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4=", :src => "https://code.jquery.com/jquery-3.2.1.min.js"}
:javascript
  function initMap() {

      let atnu = {lat: 48.915827, lng: 24.711436};
      let map = new google.maps.Map(document.getElementById('map'), {
          zoom: 15,
          center: atnu
      });
      let marker = new google.maps.Marker({
          position: atnu,
          map: map
      });
  }
%script{:async => "", :defer => "defer", :src => "https://maps.googleapis.com/maps/api/js?key=AIzaSyBR9hWhE7KItgdqZbFvsQpwDWwP9vLf1r0&callback=initMap"}

app/views/layouts/application.html.haml
= content_for body_class: 'home'

!!!
%html
  %head
    %meta{content: 'text/html; charset=UTF-8; IE=edge', 'http-equiv' => 'X-UA-Compatible'}/
    %title Home
    %meta{name: 'viewport', content: 'width=device-width, initial-scale=1, maximum-scale=1'}

    %link{rel: 'shortcut-icon', href: 'favicon.ico', type: 'image/x-icon'}
    %link{rel: 'beard-icon', href: 'beard.png'}
    %link{rel: 'beard-icon', sizes: '72x72', href: 'beard-72.png'}
    %link{rel: 'beard-icon', sizes: '114x114', href: 'beard-114.png'}
    = csrf_meta_tags
    = stylesheet_link_tag 'application', media: 'all'
    = stylesheet_link_tag 'https://fonts.googleapis.com/css?family=Open+Sans:300,400,600'
    = javascript_include_tag "application"
    = javascript_include_tag "http://maps.googleapis.com/maps/api/js?sensor=false"
  %body{class: yield(:body_class)}
    = render 'partials/menu'
    - if request.url != root_url
      .wrapper
        = yield
        = render 'partials/footer' if request.url != root_url
    = yield if request.url == root_url
    #opacity-bg

app/views/main/index.html.haml
%section.wrapper-content
  .academy-container.home
    .academy-bg.home-academy-bg
    .academy-overlay-wrap
      .academy-overlay-container
        .academy-overlay-content
          .container.fullsize
            .row
              %h1.col-md-10.home-title.col-md-offset-1
                Академія технічних
                %br/
                наук України
          .container
            .row.home-text
              %span.col-md-12.home-subtitle.has-line-top Вдосконалюй себе разом з нами
            .row.button-wrapper
              .col-md-12.button-news
                = link_to 'Перейти до новин', news_index_url, {class: 'call-upcomes-lectures'}

app/views/monographs/ended.html.haml
%main.main-container
  .container
    - @monographs.each_slice(3) do |monographs|
      .row
        - monographs.each do |monograph|
          .col-md-4.news-box
            .box-item
              %span.date
                = monograph.authors
              %span.date файл PDF
              %span.title
                = monograph.name
              = link_to 'Завантажити', monograph.file_url, {class: 'about-link'}
    .row
      %nav.pull-right
        = will_paginate @confereces, {renderer: BootstrapPagination::Rails, previous_label: '<<', next_label: '>>'}

app/views/monographs/future.html.haml
%main.main-container
  .container
    %h1.text-center Формування авторського колективу
    - @monographs.each_slice(3) do |monographs|
      .row
        - monographs.each do |monograph|
          .col-md-4.news-box
            .box-item.show-monographs
              .js-element-id{hidden: ""}
                = monograph.id
              %span.date
                Редактори:
                = monograph.authors
              %span.date
                = monograph.author_email
              %span.title
                = monograph.name
              = content_tag(:button, content_tag(:span, 'Заявка'), class:['js-request','about-link'], data: {id: monograph.id.to_s})
#js-modal-request.modal.modal-request-monographs
  #js-close-modal.close-modal
    %span.glyphicon.glyphicon-remove
  = form_with url: monograph_registration_url, local: true do |f|
    %h3.title-form Заявка
    .group
      = f.hidden_field :monograph_id, id: 'object-id'
      = f.text_field :first_name, { required: true }
      %span.highlight
      %span.bar
      = f.label :first_name, 'Прізвище'
    .group
      = f.text_field :last_name, { required: true }
      %span.highlight
      %span.bar
      = f.label :second, 'Імʼя'
    .group
      = f.text_field :surname, { required: true }
      %span.highlight
      %span.bar
      = f.label :surname, 'По батькові'
    .group
      = f.text_field :phone, { required: true }
      %span.highlight
      %span.bar
      = f.label :phone, 'Телефон'
    .group
      = f.text_field :email, { required: true }
      %span.highlight
      %span.bar
      = f.label :email, 'E-mail'
    .btn-box
      = f.submit 'Відправити', class: 'btn btn-submit', id: 'save'
  .row
    %nav.pull-right
      = will_paginate @confereces, {renderer: BootstrapPagination::Rails, previous_label: '<<', next_label: '>>'}

app/views/news/index.html.haml
%main.main-container
  .container
    .row
      %h1.title-wrapper Новини
    - @news.each_slice(5) do |news|
      .row
        - news.first(3).each do |news_3|
          .col-md-4.news-box
            .box-item
              %span.date
                = news_3.created_at.strftime("%Y-%m-%d")
              %span.title
                = news_3.name
              = link_to 'Читати далі...', news_url(news_3.id), class: 'about-link'
      - if news.count > 3
        .row
          - news.last(2).each do |news_2|
            .col-md-6.news-box
              .box-item
                %span.date
                  = news_2.created_at.strftime("%Y-%m-%d")
                %span.title
                  = news_2.name
                = link_to 'Читати далі...', news_url(news_2.id), class: 'about-link'
    .row
      %nav.pull-right
        = will_paginate @news, {renderer: BootstrapPagination::Rails, previous_label: '<<', next_label: '>>'}

app/views/news/show.html.haml
.container
  .row
    .col-xs-12
      %h1.title__item-news
        = @news.name
      -# .image__item-news
        %img.img-responsive{:alt => "", :src => "img/slider/1.jpg"}/
      %span.date__item-news
        = @news.created_at.strftime("%Y-%m-%d")
      .text-container__item-news
        %p
          = @news.description

app/views/partials/_footer.html.haml
%footer#footer.footer.navbar-fixed-bottom
  .container
    %p.text-copyright ATNU © Copyright 2017. All Rights Reserved.
    %p.text-made Made by student IT UKD

app/views/partials/_menu.html.haml
%section.academy-menu
  .container
    .main-logo
      = link_to root_url do
        = image_tag 'logo.png'
    %nav.main-menu
      %ul.main-menu-parent
        %li.menu-parent
          = link_to 'Новини', news_index_url
        %li.menu-parent
          %a{:alt => 'Конференції'}
            Конференції
            %i.fa.fa-chevron-down
          %ul.main-menu-child
            %li.menu-child
              = link_to 'Майбутні', conferences_future_url
            %li.menu-child
              = link_to 'Проведені', conferences_ended_url
        %li.menu-parent
          %a{:alt => "Монографії"}
            Монографії
            %i.fa.fa-chevron-down{"aria-hidden" => "true"}
          %ul.main-menu-child
            %li.menu-child
              = link_to 'Майбутні', monograph_future_url
            %li.menu-child
              = link_to 'Видані', monograph_ended_url
        %li.menu-parent.contacts
          = link_to 'Контакти', contacts_url
    .mobile-bars
      %i.fa.fa-bars{"aria-hidden" => "true"}